# Generated by Django 5.1 on 2024-09-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reiview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reiview',
        ),
    ]
